# Generated by Django 6.0.2 on 2026-07-13 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='address',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='producer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producer',
            name='lead_time_hours',
            field=models.PositiveSmallIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_notes',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(default='Assessment test gateway', max_length=30)),
                ('status', models.CharField(default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='marketplace.order')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producer_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='marketplace.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to='marketplace.producer')),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='supplier_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketplace.supplierorder'),
        ),
        migrations.AddConstraint(
            model_name='supplierorder',
            constraint=models.UniqueConstraint(fields=('order', 'producer'), name='one_supplier_order_per_producer'),
        ),
    ]
